<a href="https://colab.research.google.com/github/KiranSinha872/data_science_june/blob/main/pandasPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('student_data.csv')
df.head(5)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [6]:
df.describe()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [9]:
df.shape

(10000, 8)

In [10]:
df.columns

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

In [11]:
df.index

RangeIndex(start=0, stop=10000, step=1)

In [16]:
#select a column
new_df=df["attendance"]
new_df

0       56
1       69
2       60
3       99
4       52
        ..
9995    58
9996    98
9997    44
9998    75
9999    70
Name: attendance, Length: 10000, dtype: int64

In [21]:
x=df.loc[1,'attendance']
display(f" atatance is {x}")

' atatance is 69'

In [25]:
df.iloc[0:5,0:1]

   study_hours
0            7
1            4
2           11
3            8
4            5

In [27]:
df['new_column']='values'
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,new_column
0,7,56,8,7,10,62,100.00,Placed,values
1,4,69,5,3,8,56,100.00,Placed,values
2,11,60,7,6,10,45,100.00,Placed,values
3,8,99,9,8,4,55,90.17,Placed,values
4,5,52,8,6,8,40,78.82,Placed,values
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,values
9996,7,98,6,9,4,87,100.00,Placed,values
9997,10,44,8,5,10,37,95.94,Placed,values
9998,10,75,7,5,8,52,88.61,Placed,values
9999,2,70,6,11,16,52,78.96,Placed,values

In [32]:
df.rename(columns={'new_column':'trail'},inplace =True)
df.rename(index={2:23},inplace=True)
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,trail
0,7,56,8,7,10,62,100.00,Placed,values
1,4,69,5,3,8,56,100.00,Placed,values
23,11,60,7,6,10,45,100.00,Placed,values
3,8,99,9,8,4,55,90.17,Placed,values
4,5,52,8,6,8,40,78.82,Placed,values
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,values
9996,7,98,6,9,4,87,100.00,Placed,values
9997,10,44,8,5,10,37,95.94,Placed,values
9998,10,75,7,5,8,52,88.61,Placed,values
9999,2,70,6,11,16,52,78.96,Placed,values

In [53]:
print(df.columns)
print(df.index)

# df.drop('trail',axis=1,inplace=True)

df.drop(5, axis=0, inplace=True)
df

Index(['study_hours', 'attendance', 'sleep_hours', 'assignments_completed',
       'exam_score', 'placement_status'],
      dtype='object')
Index([   0,    1,    3,    4,    5,    6,    7,    8,    9,   10,
       ...
       9990, 9991, 9992, 9993, 9994, 9995, 9996, 9997, 9998, 9999],
      dtype='int64', length=9998)

,study_hours,attendance,sleep_hours,assignments_completed,exam_score,placement_status
0,7,56,8,10,100.00,Placed
1,4,69,5,8,100.00,Placed
3,8,99,9,4,90.17,Placed
4,5,52,8,8,78.82,Placed
6,10,40,4,9,98.12,Placed
...,...,...,...,...,...,...
9995,2,58,9,8,69.31,Not Placed
9996,7,98,6,4,100.00,Placed
9997,10,44,8,10,95.94,Placed
9998,10,75,7,8,88.61,Placed
9999,2,70,6,16,78.96,Placed

In [55]:
x=df.sort_values(by='study_hours')
display(x)

,study_hours,attendance,sleep_hours,assignments_completed,exam_score,placement_status
7255,1,69,7,16,63.95,Not Placed
7251,1,75,5,6,54.50,Not Placed
7250,1,73,5,12,74.72,Placed
5677,1,41,8,19,55.04,Not Placed
5713,1,97,7,13,84.56,Placed
...,...,...,...,...,...,...
9969,11,84,8,3,100.00,Placed
127,11,75,6,5,96.23,Placed
9955,11,82,8,1,100.00,Placed
29,11,63,9,1,96.59,Placed
9958,11,87,6,16,100.00,Placed

In [56]:
y=df.sort_index()
display(y)

,study_hours,attendance,sleep_hours,assignments_completed,exam_score,placement_status
0,7,56,8,10,100.00,Placed
1,4,69,5,8,100.00,Placed
3,8,99,9,4,90.17,Placed
4,5,52,8,8,78.82,Placed
6,10,40,4,9,98.12,Placed
...,...,...,...,...,...,...
9995,2,58,9,8,69.31,Not Placed
9996,7,98,6,4,100.00,Placed
9997,10,44,8,10,95.94,Placed
9998,10,75,7,8,88.61,Placed
9999,2,70,6,16,78.96,Placed

In [58]:
print(df['study_hours'].unique())
print(df['study_hours'].nunique())

[ 7  4  8  5 10  3 11  6  2  1  9]
11

In [59]:
a=df.agg({
    'study_hours':['min','max','mean'],
    'attendance':['min','max','mean']
})
display(a)

      study_hours  attendance
min      1.000000   40.000000
max     11.000000  100.000000
mean     5.989097   69.886766

In [64]:
l=df.groupby('placement_status')['exam_score'].mean()
display(l)

placement_status
Not Placed    26.67
Placed        70.02
Name: exam_score, dtype: float64

In [69]:
students = pd.DataFrame({
    'student_id': [1, 2, 3],
    'name': ['Kiran', 'Rahul', 'Aman']
})
scores = pd.DataFrame({
    'student_id': [1, 2, 4],
    'score': [90, 85, 95]
})

m=pd.merge(students,scores,on='student_id',how='outer')
display(m)

   student_id   name  score
0           1  Kiran   90.0
1           2  Rahul   85.0
2           3   Aman    NaN
3           4    NaN   95.0